version: '3.1'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_kjak
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kjak2kjak
      MYSQL_DATABASE: kjakdb
      MYSQL_USER: kjakuser
      MYSQL_PASSWORD: kjak2kjak
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
